export const booksStrategy = [
    { PT: "Gênesis", EN: "Genesis" },
    { PT: "Êxodo", EN: "Exodus" },
    { PT: "Levítico", EN: "Leviticus" },
    { PT: "Números", EN: "Numbers" },
    { PT: "Deuteronômio", EN: "Deuteronomy" },
    { PT: "Josué", EN: "Joshua" },
    { PT: "Juízes", EN: "Judges" },
    { PT: "Rute", EN: "Ruth" },
    { PT: "1 Samuel", EN: "1 Samuel" },
    { PT: "2 Samuel", EN: "2 Samuel" },
    { PT: "1 Reis", EN: "1 Kings" },
    { PT: "2 Reis", EN: "2 Kings" },
    { PT: "1 Crônicas", EN: "1 Chronicles" },
    { PT: "2 Crônicas", EN: "2 Chronicles" },
    { PT: "Esdras", EN: "Esdras" },
    { PT: "Neemias", EN: "Nehemiah" },
    { PT: "Ester", EN: "Esther" },
    { PT: "Jó", EN: "Job" },
    { PT: "Salmos", EN: "Psalms" },
    { PT: "Provérbios", EN: "Proverbs" },
    { PT: "Eclesiastes", EN: "Ecclesiastes" },
    { PT: "Cântico dos Cânticos", EN: "Song of Songs (Canticles)" },
    { PT: "Isaías", EN: "Isaiah" },
    { PT: "Jeremias", EN: "Jeremiah" },
    { PT: "Lamentações", EN: "Lamentations" },
    { PT: "Ezequiel", EN: "Ezekiel" },
    { PT: "Daniel (Teodócio)", EN: "Daniel (Theodotion)" },
    { PT: "Oseias", EN: "Hosea" },
    { PT: "Joel", EN: "Joel" },
    { PT: "Amós", EN: "Amos" },
    { PT: "Obadias", EN: "Obadiah" },
    { PT: "Jonas", EN: "Jonah" },
    { PT: "Miquéias", EN: "Micah" },
    { PT: "Naum", EN: "Nahum" },
    { PT: "Habacuque", EN: "Habakkuk" },
    { PT: "Sofonias", EN: "Zephaniah" },
    { PT: "Ageu", EN: "Haggai" },
    { PT: "Zacarias", EN: "Zechariah" },
    { PT: "Malaquias", EN: "Malachi" },

    // Apócrifos
    { PT: "1 Macabeus", EN: "1 Maccabees" },
    { PT: "2 Macabeus", EN: "2 Maccabees" },
    { PT: "3 Macabeus", EN: "3 Maccabees" },
    { PT: "4 Macabeus", EN: "4 Maccabees" },
    { PT: "Baruc", EN: "Baruch" },
    {
        PT: "Bel e o Dragão (Versão LXX antiga)",
        EN: "Bel and the Dragon (Old LXX Version)",
    },
    { PT: "Epístola de Jeremias", EN: "Epistle of Jeremiah" },
    { PT: "Judite", EN: "Judith" },
    { PT: "Odes", EN: "Odes" },
    { PT: "Salmos de Salomão", EN: "Psalms of Solomon" },
    { PT: "Eclesiástico (Sirácida)", EN: "Sirach (Ecclesiasticus)" },
    { PT: "Susana (Teodócio)", EN: "Susanna (Theodotion)" },
    {
        PT: "Tobias (Códice Sinaítico)",
        EN: "Tobit (Codex Sinaiticus)",
    },
    { PT: "Sabedoria de Salomão", EN: "Wisdom of Solomon" },
];

const secondaryBooksStrategy = {
    JoshB: { PT: "Josué B", EN: "Joshua B" },
    JudgB: { PT: "Juízes B", EN: "Judges B" },

    TobBA: {
        PT: "Tobias (Códice Vaticano)",
        EN: "Tobit (Codex Vaticanus)",
    },

    BelTh: {
        PT: "Bel e o Dragão (Teodócio)",
        EN: "Bel and the Dragon (Theodotion)",
    },
    DanOG: {
        PT: "Daniel (Versão LXX antiga)",
        EN: "Daniel (Old LXX Version)",
    },
    SusOG: {
        PT: "Susana (Versão LXX antiga)",
        EN: "Susanna (Old LXX Version)",
    },
};
